// Code generated by command: go run transpose_amd64_asm.go -out ../transpose128_amd64.s -stubs ../transpose128_amd64.go -pkg sm4bs. DO NOT EDIT.

//go:build amd64 && gc && !purego

package sm4bs

// Bit level matrix transpose, 64x128
func transpose64(in *byte, out *byte)

// Bit level matrix transpose, 128x64
func transpose64Rev(in *byte, out *byte)

// Bit level matrix transpose, 128x128
func transpose128(in *byte, out *byte)

// out = x xor y
func xor32x128(x *byte, y *byte, out *byte)

// 16 bytes per bit
func expandRoundKey128(x uint32, out *byte)

// sbox128, 128 bits per 'byte'
func sbox128(x *byte, buffer *byte)
